### PR TITLE
improve aws profile autocomplete

### PR DESCRIPTION
**Pull request by sanyer**
search also ~/.aws/config file

### CODE REVIEW

**Comment by halostatue** [comment]
This could also be written , for Fish v3, as:

```fish
cat ~/.aws/{config,credentials} | string replace -r -f "^\[(profile[[:space:]]*)*(.*)\]" '$2' | sort -u
```

**Comment by rohan-buechner** [comment]
Any update on this? The above code seems to work fine... what do we need to get it merged in? 🙏

**Comment by scorphus** [comment]
Hey, @rohan-buchner. Thanks for the ping regarding this PR.

I've took the liberty of updating it, as you can see. I would appreciate if you could give it a try and let me know if it works as expected.

Also let me know in case you need help testing this PR on your local/testing environment.

Thanks!

**Comment by rohan-buechner** [comment]
@scorphus the profiles below are all in the `.aws/config` file, thus the code works as is expected. Please see the little recording below.

https://user-images.githubusercontent.com/418810/156574258-416ab913-75b0-4a59-92a9-0b8437d942a6.mov

FWIW, I was not too sure how to test these dev plugin versions `omf install` (I assume there is a way I could do that). But I just manually applied the change in the PR to my local plugin.

**Comment by Jomik** [comment]
Can we merge this ? 😄

**Review by scorphus — APPROVED** [review]
Thanks for contributing, @sanyer!

**Comment by scorphus** [comment]
Thanks for the nudge, @Jomik

**Comment by sanyer** [comment]
oh wow, it's been a while now @scorphus 
I've changed two jobs already 😂 
Awesome that this is fixed now!

**Pull request merged**
